// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rythzoxaufcefwtoziyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dGh6b3hhdWZjZWZ3dG96aXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTcxMTEsImV4cCI6MjA2OTM3MzExMX0.nz0-vdhExrBrgxBbpwLx4S-eVVcK2_3i8IWFHhWmk9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
